language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python setup.py test
deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true